### ISSUE TITLE
Cannot reload a study after import point failure

### ISSUE THREAD

**Issue by fabien-ors** [GVigne/Molonari-2022#20]
- I open the study_2022,
- I import the attached Point folder (see zip file Point035.zip) => This fails for a reason that is not yet clear :
![image](https://user-images.githubusercontent.com/42615550/162188816-41df4604-fca2-42aa-b412-496a7b2a959b.png)
- I close the study and try to reopen... but it's impossible : 

```
Traceback (most recent call last):
  File "/home/fors/Projets/molonari/Molonari-2022/Molonari_2021/ihm/molonaviz/mainwindow.py", line 191, in openStudy
    self.currentStudy.loadPoints(self.pointModel)
  File "/home/fors/Projets/molonari/Molonari-2022/Molonari_2021/ihm/molonaviz/study.py", line 148, in loadPoints
    point.loadPointFromDir()
  File "/home/fors/Projets/molonari/Molonari-2022/Molonari_2021/ihm/molonaviz/point.py", line 52, in loadPointFromDir
    self.dftemp = readCSVWithDates(tempcsv)
  File "/home/fors/Projets/molonari/Molonari-2022/Molonari_2021/ihm/molonaviz/usefulfonctions.py", line 99, in readCSVWithDates
    raise LoadingError(f"{str(e)}") 
errors.LoadingError: Error : Couldn't load [Errno 2] Aucun fichier ou dossier de ce type: '/home/fors/Projets/molonari/Molonari-2022/Molonari_2021/studies/study_2022/Point035/processed_data/processed_temperatures.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fors/Projets/molonari/Molonari-2022/Molonari_2021/ihm/molonaviz/mainwindow.py", line 193, in openStudy
    raise LoadingError('points')
errors.LoadingError: Error : Couldn't load points
```

The issue doesn't occur everytime after an import failure...
I had to try several failed imports before experiencing this issue.

The problem is due to the fact that the "Point035" folder is incomplete and should be removed from the study directory.

[Point035.zip](https://github.com/GVigne/Molonari-2022/files/8442465/Point035.zip)

**Comment by fabien-ors** [comment]
This issue will be automatically closed when the importation procedure will lead to update the new SQL database (No more folder to be deleted). On the other hand, in case of failure during importation, the transaction must be rollback.

**Comment by ngiboureau** [comment]
Even if the issue would eventually be closed when the SQL procedure will work finely, I solved it by deleting the folder if incomplete.
